"""init

Revision ID: 711f921f273a
Revises: 
Create Date: 2025-05-08 15:49:22.135327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711f921f273a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_modifier_id_fkey', 'roles', type_='foreignkey')
    op.drop_constraint('roles_creator_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'modifier_id')
    op.drop_column('roles', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('modifier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_creator_id_fkey', 'roles', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('roles_modifier_id_fkey', 'roles', 'users', ['modifier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
